renderer : mediawiki
input_path : act.tex
output_path :  texla
doc_title:  Advanced_Control_Techniques
base_path: ""
collapse_content_level: 1
collapse_pages_level: 1
create_index: True 
export_format: text
export_single_pages: False
export_pages_tree: True
export_book_page: False
print_preparsed_tex: True
lang: it
plugins: [MathCheck, spaces_check, math_check_online]
plugins_configs:
    math_check_online:
        domain: wikitolearn.org
        threads: 6
